# Generated by Django 3.2.8 on 2021-11-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='cat_image',
            field=models.ImageField(blank=True, upload_to='photos/subcategories'),
        ),
    ]
